server: 
   port: 9527
spring: 
   application:
      name: springcloud-zuul-9527

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7003/eureka/
       defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/      
  instance:
    instance-id: gateway-7527.com
    prefer-ip-address: true     #访问路径可以显示IP地址  

zuul: 
  ignored-services: microservicecloud-dept
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
info: 
  app.name: springcloud-zuul9527
  company.name: www.atguigu.com
  build.artifactId: springcloud-zuul-9527
  build.version: 0.0.1-SNAPSHOT